{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "870d6527-6a3c-49b4-ae21-86a1dfc526d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import mean_squared_error, r2_score\n",
    "import plotly.express as px\n",
    " \n",
    "# Synthetic generation of data examples for training the model\n",
    "def generate_house_data(n_samples=100):\n",
    "    np.random.seed(42)\n",
    "    size = np.random.normal(1500, 500, n_samples)\n",
    "    price = size * 100 + np.random.normal(0, 10000, n_samples)\n",
    "    return pd.DataFrame({'size_sqft': size, 'price': price})\n",
    " \n",
    "# Function for instantiating and training linear regression model\n",
    "def train_model():\n",
    "    df = generate_house_data()\n",
    "    \n",
    "    # Train-test data splitting\n",
    "    X = df[['size_sqft']]\n",
    "    y = df['price']\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "    \n",
    "    # Train the model\n",
    "    model = LinearRegression()\n",
    "    model.fit(X_train, y_train)\n",
    "    \n",
    "    return model\n",
    " \n",
    "# Streamlit User Interface for Deployed Model\n",
    "def main():\n",
    "    st.title('🏠 Simple House Pricing Predictor')\n",
    "    st.write('Introduce the house size to predict its sale price')\n",
    "    \n",
    "    # Train model\n",
    "    model = train_model()\n",
    "    \n",
    "    # User input\n",
    "    size = st.number_input('House size (square feet)', \n",
    "                          min_value=500, \n",
    "                          max_value=5000, \n",
    "                          value=1500)\n",
    "    \n",
    "    if st.button('Predict price'):\n",
    "        # Perform prediction\n",
    "        prediction = model.predict([[size]])\n",
    "        \n",
    "        # Show result\n",
    "        st.success(f'Estimated price: ${prediction[0]:,.2f}')\n",
    "        \n",
    "        # Visualization\n",
    "        df = generate_house_data()\n",
    "        fig = px.scatter(df, x='size_sqft', y='price', \n",
    "                        title='Size vs Price Relationship')\n",
    "        fig.add_scatter(x=[size], y=[prediction[0]], \n",
    "                       mode='markers', \n",
    "                       marker=dict(size=15, color='red'),\n",
    "                       name='Prediction')\n",
    "        st.plotly_chart(fig)\n",
    " \n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "id": "b88319b8-cfd6-40a8-a6e7-075a60a3f0a9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
